### ISSUE TITLE
Setting up Visual Studio Code

### ISSUE THREAD

**Issue by herrblitzkrieg** [nblog/x64dbgpy3#1]
How to setup Visual Studio Code for this to work? The launch.json was helpful for the configuration, but apparently there is more to it since VSC Terminal shows a 'No module named 'httpx'' error when running 'test.py'. Please add a step-by-step example in the description.

**Comment by nblog** [comment]
`pip install -r requirements.txt`, that's it

**Comment by herrblitzkrieg** [comment]
I drank too much beer today... 😅 Yes ofc now it works fine.
