### ISSUE TITLE
无法通过ip地址连接 只能用localhost连接

### ISSUE THREAD

**Issue by Fourilace** [nblog/x64dbgpy3#2]
尊敬的作者您好 您的插件大大提升了调试的效率 感谢您的分享

 但是我发现x64dbgpy3svr只能通过localhost连接 无法用本机的ip地址连接 请问应该如何解决？(我是一个新手 想在宿主机连接vmware虚拟机中的x64dbg)

感谢您的解答
![1](https://user-images.githubusercontent.com/74593603/226089683-9d1499f2-b0c8-4f14-9d78-f9c15ac0f7fb.png)
![2](https://user-images.githubusercontent.com/74593603/226089686-39c42fe9-55d9-4ebb-8a27-27040d231cc1.png)

**Comment by nblog** [comment]
@Fourilace 已修复.
